name: Testing

on:
  workflow_call:

jobs:
  test-flutter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.8'
          channel: 'stable'

      - name: Cache pub dependencies
        uses: actions/cache@v3
        with:
          path: $/.pub-cache
          key: $-pub-$
          restore-keys: $-pub-

      - name: Clean flutter
        run: flutter clean

      - name: Import pub dependencies
        run: flutter pub get

      - name: Testing
        run: flutter test --coverage

      # - name: Upload to code coverage
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{secrets.CODECOV_TOKEN}}
      #     file: coverage/lcov.info